---
title: "About Good Discussions"
date: 2017-11-30
categories: ["teaching", "learning", "ideas"]
---

Arguing may likely be an intrinsic feature of our species, maybe our competitive edge, or even a paramount example of our Human Nature[^EnigmaReason]. Part of my decision to work in Science is because of the continuous exchange of ideas generated through formal argumentation. By formal argumentation I mean the translation of the basic principles that govern how the Universe functions into a language we can understand and share (hopefully agree upon?). But I also enjoy argumentation outside the scientific environment. For example, I deeply enjoy books on negotiation[^NeverSplit] and having hypothetical conversations in agreement/disagreement with [Sam Harris](https://soundcloud.com/samharrisorg) or [Tim Ferris](https://tim.blog/).  

I devote some time to think about discussions and debate myself about the existence of general principles that can be extracted. Such principles should *work* regardless of the context in which the discussion is happening (e.g, professional, teaching, personal).  

I have been baking some ideas, which I try to apply to the way I work with people and teach. Some of my thinking is below:  

## What makes a good discussion? 

* **Exchange of ideas.** This is more than a fundatamental principle of arguments, it is mandatory for any communication that has more than one direction of flow. [Matt Ridley](https://www.ted.com/talks/matt_ridley_when_ideas_have_sex) has made an interesting point about what are the best contexts in which this exchange happens for scientific endeavors. 

* **Defining the space of the discussion.** I detest the philosophical debate about definitions, particularly when it prevents from getting to the actual discussion. Burrying a debate in semantics is one of my greatest fears. But Philosophers understand that there is no point in trying to debate about something if we do not agree about *what that something is*. Additionally, for a discussion to be meaningful, we should agree on the terms in which we evaluate evidence and thus are allowed to make valid claims. If and only if we agree on the axioms that serve as building blocks for argumentation we might have a proper space to elaborate reasons and viewpoints (from Marvel vs DC to the Meaning of Life).

## What makes a bad discussion?

* **The agree to disagree mentality.** This exit is somewhat primitive. It shuts conversation, it stalls argumentation at a basic level. The goal of coming to an agreement is always secondary to the fact that we are exchanging ideas. The danger of this phrase is that it hides what the real problem is (the subject matter of discussion) and shifts it towards the person you are disagreeing with (e.g., because you are not smart/patient/calm/whatever enough to get this, I am no longer talking with you). Passive aggressiveness is not a constructive way to get to a disagreement. It is true that, given genuine disagreement, the real conclusion of a discussion will sound much like this phrase. However, taking this exit prematurely makes both parts end up losing, and feeling as if it the endeavour was a waste of time, while getting at the genuine point in which we disagree and understanding why we do so can be enlightening.  

* **This is not an exchange, it's a competition.** The goal of a discussion should not be to win the argument. It is not a battle, it is an exchange of ideas. Given 1) I convince you that my way of thinking makes sense and 2) If and only if my rationale is correct; Then we **both win**. Otherwise, it's a zero-sum game, or even worse, we all lose.  

* **Winner takes all mentality.** This one is very related to the previous one, but it is more dangerous. Even with a winning mentality, whoever wins does not need to be crowned master and owner of all. We need not argue *against* an opponent nor we need to completely destroy our interlocutor.   

* **You can talk but I'm not listening.** Listening does not mean that you have to agree with what it is being said. But it does mean that you are open to considering whatever argument is offered to you as valid, or even true, as long as it is sound. You need a certain mindset to be listening and actively evaluating the arguments presented. You need to be somehow outside of yourself. If any or both parts are so self-centered they cannot listen, there is no discussion. Why? Because it is not possible to have a proper exchange of ideas by taking turns in vomiting a set of words into each another. At that point, it is no longer a discussion, it shifts towards being *personal*, no longer the idea itself.

[^EnigmaReason]: Complex and highly recommended http://www.hup.harvard.edu/catalog.php?isbn=9780674368309

[^NeverSplit]: Never Split the Difference by Chris Voss https://www.goodreads.com/book/show/26156469-never-split-the-difference

