---
title: "The power of compounding"
date: 2020-01-20
---

Paying attention to the small details sounds like a waste of time. Where's that 80/20 rule when I need it? Well, yes, talking about a small increment sounds boring and useless. A 1% increase in performance might seem trivial. Unexciting. A rounding error. 

But it is often neglected because we don't have a good dimension of scales (e.g., A small percent of a lot of money it's a lot of money) or even when we do, we fail to grasp what exponential phenomena look like. For example, if I double the amount of water on a glass each time I pour water into it, you will see the glass go from half empty to overfull in one round. Yes, doubling is a way bigger rate than 1% increase, but I don't want to get into math[^unless]. I'm actually using *compounding* in quite a loose way. 

[^unless]: unless you read until the end, when the 1% comes for the revenge!


Moreover:

> It's not only what the 1% can do for you now, it's what it will do for you from now on.

## Happiness

How did we get to happiness? I don't really know. I guess I just noticed that a couple of very small details, small daily decisions, have a tremendous impact in the way I feel, and the mental freedom that they bring is quite refreshing. We know what they are: eating healthy, sleeping well, moving the butt away from the chair and shaking it whatever way you fancy! 

Take meditation and the power of breathing. Simple, right? Well, not really, and it will take a while for you to set it up right. Eventually, you will be able to access the power in one breath. But it will not happen the first time you sit for a session. You need to keep your mind on breath after breath, minute after minute of being present. What you need is a **system**. And you need **patience** for letting your system to do the work.

One mindful breath is inconsequential, just an infinitesimal drop in the Universe of mindless breathing. But what happens when you start practicing, compounding the power of the infinitesimal? Can you feel the difference? Me too. 

## Investing

It's no secret that all investment revolves around compounding. Set up your systems (aka, allocate your money) and let it run. I just thought I would remark words of a wise investor, letting us know that, even when we are talking about money, compounding is king but takes a little while to show up to the party.

> Patience and optimism are also keys to investing success. Patience because it takes time for the power of compounding to unfold. Optimism because we have to trust the future will allow it the opportunity.[^jcollins]

## Relationships

What if we apply the power of compounding to our relationships? How many more times are you going to suffer because of someone? I will give you a small system: two questions and one quote. 

1. What if you stopped hanging around people who bring conflict and suffering? 
2. What if you started hanging around people who don't bring conflict and suffering?

> The first rule of handling conflict is don't hang around people who are constantly engaging in conflict. (. . .) All of the value in life, including in relationships, comes from compound interest. People who regularly fight with others will eventually fight with you. I'm not interested in anything that's unsustainable or even hard to sustain, including difficult relationships. -- Naval Ravikant

## Summary

I hear what you are saying, *Setting systems up is boring*. Maybe. *You have to troubleshoot them, you have to stress test them*. True. *Moreover, once you have them, they still haven't solved the problem that first got you to think about setting them up*. Of Course! You will find yourself asking whether your systems will ever accomplish something. This is because they actually do nothing for a while. Their power lives in the compounding, it feeds from the amount of time that the system has been running.

Setting up systems is the best way to get rid of your problems. Why? Because once you have systems, your problems are no longer yours, they belong to the systems that you put in place. Slowly, but surely, your systems will kick ass.

A random tweet reminded me that a small improvement each day for a year can make a big difference. Simple and to the point, the power of compounding:

```
1.01³⁶⁵ ≈ 37.78
```

What will you apply this power to?


[^jcollins]: I couldn't have said this better, so I quote [JL Collins](https://jlcollinsnh.com/2018/06/07/stocks-part-xxxiii-optimism/)
