---
title: Writing challenge Day 7
date: 2018-09-05
output: html_document
categories: ["writing", "DocumentingLearning"]

---

This week, I did a couple of new things:

* I moved to Boston.
* I started a new job.
* I started writing *almost* every day.

Out of these three things, writing has proven to be the most challenging. 

However, it's increasingly building into a good habit. I can feel somewhere in my brain a voice that tells me *"we have to write today"*. Even though I was not planning to write the article today, I ended up going for it anyways. As it turns out, it has been a week since I started, so I should just go to report it.  

Here's how the first week looks like:

```{r}
#| echo: false
#| message: false
library(dplyr, warn.conflicts = F)
tracking_writing <- read.csv("tracking_writing.csv")

tracking_writing <- dplyr::select(tracking_writing, -place) %>%
  mutate(date=lubridate::ymd(date)) %>% 
  filter(date < as.Date("2018-09-05"))

knitr::kable(tracking_writing, align = 'c')

```

## Thoughts

Some early but general comments/thoughts about the challenge:

* **I appear to be more willing to write after dinner and late into the night.** This might not be because I am naturally better at this moment, it's just better for my schedule to be expedite in the morning (the time between wake-up and the moment I leave is normally less than an hour). This decision leaves no room for writing in the mornings except for weekends. 

* **Writing in the morning can feel great too!** Indeed, on September 1st I wrote during the morning and it was great. I knew I was going to be literally dead after the move, so I allowed myself to be happy with my small writing after breakfast. It didn't feel weird to write in the morning at all, and I was full of energy after a pretty charged breakfast.  

* **I am always below the word count goal.** My current writing reaches somewhere between 1000-1300 a day, which gets considerably easier if I know what I'm gonna be writing about, or if I have a somewhat detailed outline. On the contrary, being tired (like right now when I'm writing this first draft) makes it really tough to find creative paths. Maybe that's why I chose a *report-like* structure for this post. I am not super concerned because I already feel some improvements and because **2000 words a day is a lot**. It's a nice goal to have and I can probably do it sooner than later. I can probably also run 5K a day too, and bake a cake after that, and cook dinner, and never sleep? 

## The setup

I have a fair amount of ongoing projects. The ones that are especially out of control are the fiction stories/novels I write for fun. I have been thinking about closing all those loops for a long time, having the *unfinished* folder uncluttered would be beautiful. These texts are partially written but in a disorganized manner that makes it hard to keep track of. Hopefully with time and the habit of writing words into text consistently they will become finished.

## The good

This challenge set me up in a good mood regarding my writing. I regained encouragement towards writing and confidence towards being able to reduce the number of *unfinished* pieces. I also feel words coming easily (and it works for Spanish too!).  

Short stories are easier to write. These take less time to outline and develop into scenes, stakes are lower and I feel them flow easier through my brain. The relatively low amount of characters makes it easy to keep track of. The [stats book](bookdown.org/matiasandina/R-intro) and novels are harder. These need more research and planning, pruning of the content. For example, triple checking the code makes sense and graphs show the way you want or that after x amount of words. 

I decided to go full Markdown from now on. Webpage and stats book are already `.Rmd`, some other note-taking things are `.md` too. I changed my `.docx` short stories into `.md`. I discovered an awesome text editor (Sublime text 3). It's everything I wanted a text editor to be. I am pretty happy with Rstudio's editor for `.Rmd` files but I find Sublime to be awesome[^sublime]. 

## The bad

I am still not organized when writing. I don't stick to the correct stages. I jump from outline to completion of the idea. Investing more into thinking about and writing proper outlines can save tremendous amount of energy/time and propel writing during the first draft.   

I took the first project at random and I did not finish that one project before continuing with another (and yet another one). It was a two-fold scenario: I felt blocked after writing a bit of the first project and all of a sudden better ideas appeared for the other projects. I did stop at 3 (out of the 30). I guess I still need to work on the completion part before jumping into new.

***

[^sublime]: I actually went into it because I really wanted something that could handle `.csv` files without changing them (Excel would do whatever it wants but keep the text as is). I had the "somebody *must have solved* this issue" feeling for so long, and now I have Sublime, pretty happy about it `:)`.
