---
title: Any Questions?
date: 2017-12-17
categories: ["teaching","learning", "DocumentingLearning"]

---

I'm writing this post to document my own learning on reading from [Teaching Tips](https://books.google.com/books/about/McKeachie_s_Teaching_Tips_Strategies_Res.html?id=v_0zqB13lW8C) and [Teaching at its Best](https://books.google.com/books/about/Teaching_at_Its_Best.html?id=NC5P8z-u-H0C). This particular post has to do with engaging students to contribute with questions to class. 


## Checking student understanding 

During class, there is a moment in which you feel that you've covered a couple of ideas in the way you wanted to and you decide to check if everything is alright. Other times, you feel as if you weren't able to convey the points in the way you wanted to. Again, the same feeling hits you and you fall into the following invitation to the students:

> Any questions?

No, no, no and no...wrong way to go! You get silence. Ten more seconds. You get looks that are impossible to decipher. Yes, if you are lucky enough you might get a hand up, willing to break the frozen air. But usually that's not the case and you get trapped into believing that, indeed, there are no questions. So, how should we foster greater participation for self-assessment in class? How can we facilitate manifestation of doubts?

I'll give more tries to this active pause method:

1. Take one minute to review your notes.
1. Write a question you would like to answer.
1. Share with a peer you questions.
1. Share with the class and/or turn in such questions.

