---
title: Writing challenge Day 1
author: "Matias Andina"
date: 2018-08-30
tags: ["research", "writing", "learning", "DocumentingLearning"]

---

It's been a while since I have several things to write in the back of my mind. I finally got the strength to commit myself to one of those goal oriented challenges: **Writing 2000 words a day.**  

It might sound like a bit much, now that I think about it, but today is Day 1 so I might as well get to do it. I have not limited the type of content I will write, my aim is to get as fluent as possible and to have writing become habitual. That means I will increase the number of posts/short stories/book chapters/papers/review papers/twitter posts.

Does coding count? Is it a line by line instead of word count? I have not started writing and I am already thinking how to cheat about it...I am not quite confident about fortune cookie writer, but, since I foresee writing to be paramount for my future, I'm 100% down to master it.  

I'm a bit obsessed about measuring stuff. Thus, I will also be implementing a suggested technique to keep a record of the data that such writing endeavor produces[^suggested]. It goes like this:

Make a table with

* Date
* Time
* Project Name
* Type of writing
* Word count
* Place

It sounds fairly easy to keep up with recording (I record so many other stuff) and there are some pieces of information that sound like really interesting to have. I have always considered myself better at night. Is it really the case? Do I write better at night or in the morning before work? Do I write better at home or somewhere else? Should I go to the international space station? Maybe that would give enough inspiration to put those works together into text like it's no big deal.  

Recording means a lot of plots (oh yes it does) and I have played a bit with calendar/github like heatmap plots before ([see here](../2018-05-27-github-style-calendar-heatmap/index.qmd)), so I will be happy to show the trends in future posts. I will also be commenting about my impressions with the technique and if I actually manage to make it a habit of mine.  

So...having written 390 words and finished my first slotted time, I should go back to my duties. Every long journey starts with a small step, writing will continue in the next scheduled period.



[^suggested]: Suggested [here](https://www.goodreads.com/book/show/18478318-writing-habit-mastery---how-to-write-2-000-words-a-day-and-forever-cure)
