---
title: About student motivation
date: 2017-12-26
categories: ["teaching","learning", "DocumentingLearning"]

---

I'm writing this post to document my own learning on reading from [Teaching Tips](https://books.google.com/books/about/McKeachie_s_Teaching_Tips_Strategies_Res.html?id=v_0zqB13lW8C) and [Teaching at its Best](https://books.google.com/books/about/Teaching_at_Its_Best.html?id=NC5P8z-u-H0C). 

I have found chapter 11 of McKeachie's to be of great value, it contains lots of starting points for discussion and further analysis.

## Choice

Humans are into the *free will thing*. Access to choosing their own topic, exam questions and due dates might facilitate the learning experience and boost motivation through a feeling of agency. However, too much choice is normally a bad thing. Assignments like "write about anything" are not a good idea. 

### I plead guilty

I have incurred in the "write about anything" practice for some of my assignments. The way I try to convince myself that the strategy works, is by saying that "I keep the range of acceptable answers broad and do not constrain individual variability". I would sometimes say that to my students, which is received with mixed feelings. There is a sweet spot of "individual variability" within a constrained playground that I should look for. Letting them on the loose ends up hindering their production and diminishing motivation.

## Value

I have previously written about value and purpose [here](/2017/11/about-teaching-nonsense/). I am really glad that many concerns I had before reading McKeachie's have also appeared as concerns for the author. It is explicitly advised to teachers: **Teach with a sense of purpose**. Moreover, one should: 

> Make the value of the course explicit and take time to help students understand why what they are learning matters.

## Teach for Mastery

What if we taught for mastery instead of grades? What if we set concrete non relative standards? Students will greater benefit from this approach. I have my own set of thoughts about teaching for mastery. For now, I will relay information better put together by people who believe what I believe, like [Salman Khan](https://www.ted.com/talks/sal_khan_let_s_teach_for_mastery_not_test_scores). On a related note, I highly recommend this book on [Mastery](https://www.goodreads.com/book/show/81940.Mastery).

> This is not a nice to have, it's a social imperative. - Salman Khan

## Praise

Reading a beautiful piece written by a student is a superb experience. Sometimes they come up with insightful ways of producing content, powered by creative thinking, showing angles you have not seen before, citing sources you totally missed or read through a different mindset. Those moments are wonderful and I thank this profession for that. Good work should be recognized and encouraged. 

But there is a potential pitfall on praising. We tend to appreciate talent over hard work. Hence we might fall on the idea that some of the students are just *naturals*, they *just have it*. Whatever that *it* is, it's extremely hard to define and completely subjective. There are interesting pieces written on appreciation of talent over working ethic like [this one](https://medium.com/personal-growth/talent-vs-hard-work-why-focus-on-hard-work-734e65a7c097) or any of the following [Google Search](goo.gl/xc7fte). Whenever encountering outstanding work, praise the work, the distilled action is the following:

> Do not praise for talent. Praise working ethic.

On a day to day basis, strive to make the correct associations. Instead of "Good job! You must be really talented" go for "Good job! You must have worked really hard".
