---
title: Russian roulette
date: 2020-11-02 
categories: ["random","investing"]
---

There are many traders and most of them blow up at some point in their careers[^1]. Maybe that's why we worship those who don't. We find rational explanations for their success, which basically boil down to saying they are smarter/faster/bolder/better than everyone else. We may even go as far as justifying success at all costs.

[^1]: A less pernicious version are those fund managers that loose money in comparison to an index fund such as the SP500 and charge a handsome fee to do so.

I'm sure there's a lot of skill involved in playing dice with such great results over such a long period of time. And I'm not writing this to indicate there's no such thing as ability involved in long-term successful investing. However, we know that things are never 100% skill and I am curious about the role of luck in performing a series of successful trades. In other words, what is the portion of *luck* involved in the process? There's a ton of traders out there [*citation needed*], shouldn't we expect the emergence of at least one Warren Buffet by *chance*?

## Warren Buffet and the Russian Roulette

Warren Buffet is quite often considered unique in the pool of people who operate on the markets. But, what does *unique* mean? In other words, how likely is that we find a Warren Buffet?

## Russian Roulette: quite good odds.

Let's play with some odds here. The Russian Roulette is that game in which you put a bullet on a six chamber revolver, you spin the barrel and pull the trigger, hoping that your attempt does not blow your brains. Not quite like taking a position on a stock, but not much different.

I will focus on the first event, the first trigger after the spin. If it turns out that the bullet is fired in the first trigger, the outcome is terrible. In other words, failure in this game equals total unrecoverable loss. However, the odds of survival are *not so bad*. Assuming the spin of the barrel is mostly governed by random processes, the odds of the bullet firing are $\frac{1}{6}$ , meaning that the survival chances are $\frac{5}{6}$. I'm quite sure the current financial system allows, and maybe encourages, traders to take higher risks of blowing up. And my guess is they sleep comfortably at night.

## One million roulettes

Let's imagine we have 1 million people playing (aka, 1 million traders, comfortably spinning barrels and triggering over and over). Let's assume that the events are independent, so traders don't affect each other and each time traders spin the barrel we have full randomness in place. The equation giving the number of survivors (*S*) over *time* is:

$S(t) = 10^6 * (\frac{5}{6})^t$

We can ask ourselves: how long does it take until there's only one standing? This last trader, the survivor of all trades, will be our Warren Buffet.

$S(t = t_{x}) = 10^0 = 10^6 * (\frac{5}{6})^{t_{x}}$

$10^{-6}= (\frac{5}{6})^{t_x}$

$\frac{-6}{log_{10}(5/6)}= t_x$

$75.9 \approx t_x$

Now we see that after 76 rounds (or trades) we are expected to have one survivor who was lucky enough to keep the bullet on the revolver and therefore their brain intact. This level of lucky is extremely profitable in a leveraged, compounding environment. It pays well to be the last one standing on the graph below.

```{r}
#| label: exponential-decay
#| message: false
#| warning: false
library(tidyverse)
tibble::tibble(time = 0:76, survivors = 10^6*(5/6)^time) %>% 
  ggplot(aes(time, survivors)) +
  geom_line() +
  geom_point(aes(x=76, y=1), size=2)+
  scale_y_continuous(labels=scales::label_number_si())+
  labs(title="Number of Russian roulette players alive",
       subtitle="Dot represents the last player standing at round 76",
       x="Round No.") +
  theme_bw()
```

### Dependency

I have assumed, just for illustration purposes, that events are random and independent. That is, traders don't influence each other and the guns spinning and are identically dominated by chance. But we know that's not a realistic picture of society.

We live and experience events in sequence. Our reason operates to explain the present using the previous conditions, even if the only real explanation is luck. Moreover, luck is nonlinear in the sense that it can create a qualitative difference. Once labeled a winner, it's awful hard to lose that label, even if actively trying. People assume that you know something, you see something they don't. You can profit from the hype, it increases your chances of survival. Luck begets more luck.

Luck begets help. The winners of just a few rounds can enjoy special treatment. For example, they would be allowed to borrow at better conditions, the equivalent of playing Russian roulette with somebody else's brain on the line. They would receive hoards of people willing to put their brains in front of the bullet in the hopes of sharing part of the proceeds. And they would have all the incentives to keep happily playing even more riskier versions of Russian roulette.
