---
title: List of Common Errors
date: 2017-12-19
categories: ["teaching","learning", "DocumentingLearning"]

---

I'm writing this post to document my own learning on reading from [Teaching Tips](https://books.google.com/books/about/McKeachie_s_Teaching_Tips_Strategies_Res.html?id=v_0zqB13lW8C) and [Teaching at its Best](https://books.google.com/books/about/Teaching_at_Its_Best.html?id=NC5P8z-u-H0C).  

## Assignments and Feedback

Chapters 7 and 8 on McKeachie's Teaching tips are quite interesting and develop different lines of thought about assignments. One thing I can relate to is the idea of providing general examples of errors students normally do. This procedure comes handy when dealing with essay questions (the ones I like far more than any other). The idea is to provide feedback that can be helpful while, at the same time, having a place for students to identify common mistakes and help them internalize good practices while writing. 

I will be developing further this idea, polishing the list and hopefully including it on my future rubrics.

1. Idea needs further development.
1. Supporting evidence is absent or insufficient. 
1. Unrelated to the question. 
